# NumPy Vectors

In [1]:
import numpy as np

a = np.random.rand(5)

In [2]:
print(a)

[0.89813184 0.9341895  0.42882046 0.93884753 0.21057206]


In [3]:
print(a.shape)

(5,)


In [4]:
print(a.T)

[0.89813184 0.9341895  0.42882046 0.93884753 0.21057206]


In [5]:
print(np.dot(a, a.T))

2.7890130944558296


In [6]:
a = np.random.randn(5,1)

In [7]:
print(a)

[[-0.70655843]
 [-0.08851809]
 [-0.25588127]
 [-1.11033331]
 [ 1.52058974]]


In [8]:
print(np.dot(a,a.T))

[[ 0.49922481  0.0625432   0.18079507  0.78451536 -1.0743855 ]
 [ 0.0625432   0.00783545  0.02265012  0.09828458 -0.1345997 ]
 [ 0.18079507  0.02265012  0.06547522  0.2841135  -0.38909043]
 [ 0.78451536  0.09828458  0.2841135   1.23284007 -1.68836145]
 [-1.0743855  -0.1345997  -0.38909043 -1.68836145  2.31219317]]
